version: "3.7"
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis
        depends_on:
            - memcached
    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"